hydra:
  launcher:
    n_jobs: 1
  sweeper:
    params:
      ++model.observation_window: 5,7,11,13,15,17,21

experiment: basicDiscrete
note: null
replicate_experiment: null
logger:
  type: wandb
  folder_path: logs
  wandb_project: gr_pursuer

env:
  size: 128
  enable_hidden_cost: false

data:
  data_runs_path: gr_pursuer/data/dataset_s{}_h{}.csv
  data_scenarios_path: gr_pursuer/data/scenarios_s{}_h{}.csv

model:
  save_path: gr_pursuer/neural/models
  observation_window: 5
  nepochs: 10
  lr: 0.0001
  num_layers: 1
  num_heads: 4
  load_model: null

defaults:
  - override hydra/launcher: joblib
